Trying to find the reason why browser raises  panicked at C:\Users\Benjamin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\sauron-core-0.70.0\src\vdom\diff.rs:175:21: Node list must have already unrolled when creating an element  error. I suspect it has something to do with left sidebar and top navbar.